### ISSUE TITLE
Tag a julia 0.4 compatible 0.0.x release

### ISSUE THREAD

**Issue by davidanthoff** [JuliaDiff/ReverseDiffSource.jl#17]
Lora only works with ReverseDiffSource.jl <0.1, so the 0.0.x release series for ReverseDiffSource needs to be maintained. 0.0.5 throws warnings on julia 0.4 release candidate. I fixed all of them [here](https://github.com/davidanthoff/ReverseDiffSource.jl/tree/julia04). That branch shouldn't be merged, but added as a release branch for the 0.0.x versions, and then a new version 0.0.6 should be tagged and released.

Things would be easier if there were tags for the released versions in the repo.

**Comment by davidanthoff** [comment]
Actually, hold that, my branch is no longer julia 0.3 compatible, which is probably also a requirement. I'll fix in a sec.

**Comment by mlubin** [comment]
CC @scidom

**Comment by davidanthoff** [comment]
Alright, the branch should now be compatible with julia 0.3 and 0.4. I dropped julia 0.2 support, assuming/hoping that no one is using that anymore...

**Comment by scidom** [comment]
Thanks @davidanthoff, @mlubin, I merged the PR on the Lora side of things, but will give @fredo-dedup the space to sort out the ReverseDiffSource end given that he knows the codebase better.

@fredo-dedup I was looking at your great package and found out that the README needs updating to catch up with Julia 0.4, as I think it currently describes the older API. I just want to get used to your package so that I can see how it will work with the new face of Lora :)

**Comment by fredo-dedup** [comment]
Thanks @davidanthoff, I think I could create a branch for that specific need.

**Comment by fredo-dedup** [comment]
Found out that the branch existed already (`newoldversion`). I created a branch `lora-branch` anyway that better states its purpose. Your changes are included
I am now waiting for v0.1.4 PR to be merged in METADATA, before submitting the v0.0.6 PR.

**Comment by davidanthoff** [comment]
Excellent, thanks!

**Comment by fredo-dedup** [comment]
METADATA is updated by now.
