### ISSUE TITLE
Possibly wrong derivatives for tensors

### ISSUE THREAD

**Issue by dfdx** [JuliaDiff/ReverseDiffSource.jl#47]
Let's say we have expression `z = sum(W * x)` and want to find derivative `dz / dx`. If I run
```
rdiff(:(sum(W*x)), W=Matrix{Float64}, x=Vector{Float64})
```
I get:
```
quote 
    _tmp1 = W * x
    _tmp2 = size(_tmp1)
    _tmp3 = zeros(_tmp2) + ones(_tmp2)
    (sum(_tmp1),zeros(size(W)) + _tmp3 * x',zeros(size(x)) + W' * _tmp3)
end
```
So `rdiff` tells us that (after substitution and simplifications): 

```
dz / dx = W' * ones(size(z))
```
I haven't found any ready-to-use rules or tools to verify it, but here's my attempt to find the same derivative componentwise. If we set:

![](https://latex.codecogs.com/gif.latex?y%20%3D%20W%20%20x)

then we can rewrite equation componentwise: 

![](https://latex.codecogs.com/gif.latex?y_i%20%3D%20%5Csum_k%20W_%7Bik%7Dx_k)
![](https://latex.codecogs.com/gif.latex?z%20%3D%20%5Csum_i%20y_i)

and so:

![](https://latex.codecogs.com/gif.latex?z%20%3D%20%5Csum_i%20%5Csum_k%20W_%7Bik%7Dx_k)

Derivative of `z` w.r.t. to k-th component of `x` is thus:

![](https://latex.codecogs.com/gif.latex?%5Cfrac%7Bdz%7D%7Bdx_k%7D%20%3D%20%5Cfrac%7Bd%7D%7Bdx_k%7D%20%5Csum_i%20%5Csum_k%20W_%7Bik%7Dx_k%20%3D%20%5Csum_i%20W_%7Bik%7D)

We can organize component derivatives into a vector and get, for example:

```
dz/dx = sum(W, 2)
```
or into a row matrix and get: 

```
dz/dx = sum(W, 1)
```
In either way, this expression doesn't conform to what `rdiff` currently generates, neither in contents nor even in shape of the derivative (matrix vs. vector).

Is it a bug or am I just misusing `rdiff`?

**Comment by fredo-dedup** [comment]
For `dz / dx` we are expecting a vector of the same size as `x`. You are right that it is equal to `sum(W,1)`or more precisely its transpose  `sum(W,1)'`  (one minor difference is that this will be a column matrix instead of a vector in julia).
And unless i am mistaken we have `sum(W,1)' = W' * ones(size(z))`, no ? (the added advantage of the expression `W' * ones(size(z))` is that it will be a vector as expected for a derivative 'd./dx', and not a column matrix as with `sum(W,1)'`   )

**Comment by dfdx** [comment]
Ah, now I see. Thanks for clarification.
